server.port=8081
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=teamcle
spring.datasource.password=Tricycle1!@
spring.datasource.url=jdbc:mariadb://175.195.148.148:3306/board
spring.jpa.open-in-view=false